services:
  db:
    image: pgvector/pgvector:0.8.0-pg15
    container_name: postgres_container
    restart: always
    environment:
      POSTGRES_USER: ayush
      POSTGRES_PASSWORD: mypassword
      POSTGRES_DB: mydatabase
    ports:
      - "5432:5432"   # expose for pgAdmin or host
    volumes:
      - postgres_data:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: pgadmin_container
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD}
    ports:
      - "5050:80"
    depends_on:
      - db

  pipeline:   # 👈 your Python app
    build: .
    container_name: pipeline_container
    restart: always
    depends_on:
      - db
    environment:
      DB_NAME: mydatabase
      DB_USER: ayush
      DB_PASSWORD: mypassword
      DB_HOST: db      # 👈 service name, not localhost
      DB_PORT: 5432
    command: ["python", "-m", "src.data_pipeline.main"]

volumes:
  postgres_data: